"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Job = { id:number; company:string; companyInitials:string; companyColour:string; position:string; industry:string; employmentType:string; description:string; responsibilities:string[]; yearsExperience:number; salaryMin:number; salaryMax:number; location:string; workMode:string; visaRequirement:string; applicationDeadline:string; postedAt:string; skills:string[] };
type StudentRow = { id:number; name:string; email:string; university:string; major:string; graduationDate:string; visaStatus:string; preferredPositions:string[]; preferredLocations:string[]; skills:string[]; matches:{id:number;position:string;company:string;score:number}[] };
const dollars = (value:number) => new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(value);

function JobEditor({ job, onClose, onSaved }: { job?: Job | null; onClose:()=>void; onSaved:()=>void }) {
  const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError("");const input=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/admin/jobs",{method:job?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...input,id:job?.id})});setSaving(false);if(!response.ok){const data=await response.json();return setError(data.error??"Could not save job.");}onSaved();};
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="admin-modal" role="dialog" aria-modal="true" onMouseDown={(event)=>event.stopPropagation()}><header><div><span className="eyebrow">Opportunity details</span><h2>{job?"Update job":"Post a new job"}</h2></div><button className="icon-button" onClick={onClose}>×</button></header><form onSubmit={submit} className="admin-job-form"><label>Company<input name="company" defaultValue={job?.company??""} required /></label><label>Position<input name="position" defaultValue={job?.position??""} required /></label><label>Industry<input name="industry" defaultValue={job?.industry??"Technology"} required /></label><label>Employment type<input name="employmentType" defaultValue={job?.employmentType??"Graduate program"} required /></label><label>Location<input name="location" defaultValue={job?.location??"Sydney"} required /></label><label>Work mode<select name="workMode" defaultValue={job?.workMode??"Hybrid"}><option>On-site</option><option>Hybrid</option><option>Remote</option><option>Flexible</option></select></label><label>Minimum salary<input name="salaryMin" type="number" defaultValue={job?.salaryMin??65000} required /></label><label>Maximum salary<input name="salaryMax" type="number" defaultValue={job?.salaryMax??80000} required /></label><label>Experience required<input name="yearsExperience" type="number" min="0" defaultValue={job?.yearsExperience??0} required /></label><label>Application deadline<input name="applicationDeadline" type="date" defaultValue={job?.applicationDeadline.slice(0,10)??""} required /></label><label className="span-2">Required skills<input name="skills" defaultValue={job?.skills.join(", ")??""} placeholder="Python, SQL, Tableau" required /></label><label className="span-2">Visa requirement<input name="visaRequirement" defaultValue={job?.visaRequirement??"Australian work rights required"} required /></label><label className="span-2">Description<textarea name="description" defaultValue={job?.description??""} required /></label><label className="span-2">Responsibilities<textarea name="responsibilities" defaultValue={job?.responsibilities.join("\n")??""} placeholder="One responsibility per line" required /></label>{error?<p className="form-error span-2">{error}</p>:null}<footer className="span-2"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Saving…":job?"Save job":"Publish job"}</button></footer></form></section></div>;
}

export function AdminDashboard({adminEmail,initialJobs,students}:{adminEmail:string;initialJobs:Job[];students:StudentRow[]}) {
  const router=useRouter();const [tab,setTab]=useState<"jobs"|"students">("jobs");const [editor,setEditor]=useState<Job|null|undefined>(undefined);const [expanded,setExpanded]=useState<number|null>(null);
  const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});router.push("/login");router.refresh();};
  const remove=async(job:Job)=>{if(!window.confirm(`Delete ${job.position} at ${job.company}?`))return;await fetch(`/api/admin/jobs?id=${job.id}`,{method:"DELETE"});router.refresh();};
  return <div className="admin-shell"><aside className="admin-sidebar"><div className="logo"><span>p</span><strong>pathway</strong></div><small>ADMIN CONSOLE</small><nav><button className={tab==="jobs"?"active":""} onClick={()=>setTab("jobs")}>▣ Job listings <b>{initialJobs.length}</b></button><button className={tab==="students"?"active":""} onClick={()=>setTab("students")}>◎ Students <b>{students.length}</b></button></nav><div className="admin-account"><span>AD</span><div><strong>Administrator</strong><p>{adminEmail}</p></div><button onClick={logout}>Sign out</button></div></aside><main className="admin-main"><header><div><span className="eyebrow">Pathway operations</span><h1>{tab==="jobs"?"Job listings":"Student profiles & matches"}</h1><p>{tab==="jobs"?"Create and maintain the opportunities students are matched against.":"Review student profiles and the opportunities ranked for each person."}</p></div>{tab==="jobs"?<button className="primary-button admin-add" onClick={()=>setEditor(null)}>＋ Post a job</button>:null}</header><section className="admin-stats"><article><span>Open jobs</span><strong>{initialJobs.length}</strong><em>Across {new Set(initialJobs.map(job=>job.industry)).size} industries</em></article><article><span>Student profiles</span><strong>{students.length}</strong><em>{students.length} active this term</em></article><article><span>Strong matches</span><strong>{students.reduce((sum,s)=>sum+s.matches.filter(m=>m.score>=85).length,0)}</strong><em>85% fit or higher</em></article></section>
  {tab==="jobs"?<section className="admin-table-card"><div className="table-toolbar"><h2>All opportunities</h2><span>{initialJobs.length} records</span></div><div className="table-scroll"><table><thead><tr><th>Role</th><th>Location</th><th>Salary</th><th>Deadline</th><th>Skills</th><th /></tr></thead><tbody>{initialJobs.map(job=><tr key={job.id}><td><div className="admin-role"><span style={{background:job.companyColour}}>{job.companyInitials}</span><div><strong>{job.position}</strong><small>{job.company} · {job.employmentType}</small></div></div></td><td>{job.location}<small>{job.workMode}</small></td><td>{dollars(job.salaryMin)}–{dollars(job.salaryMax)}</td><td>{new Date(job.applicationDeadline).toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"})}</td><td><div className="tiny-skills">{job.skills.slice(0,3).map(skill=><span key={skill}>{skill}</span>)}</div></td><td><div className="row-actions"><button onClick={()=>setEditor(job)}>Edit</button><button onClick={()=>remove(job)}>Delete</button></div></td></tr>)}</tbody></table></div></section>
  :<section className="student-admin-list">{students.map(student=><article key={student.id} className={expanded===student.id?"expanded":""}><button className="student-summary" onClick={()=>setExpanded(expanded===student.id?null:student.id)}><span className="student-avatar">{student.name.split(" ").map(p=>p[0]).join("")}</span><div><strong>{student.name}</strong><small>{student.major} · {student.university}</small></div><span>{student.preferredLocations[0]}</span><div className="top-match"><b>{student.matches[0]?.score??0}%</b><small>top match</small></div><i>{expanded===student.id?"−":"＋"}</i></button>{expanded===student.id?<div className="student-detail"><div><h3>Profile</h3><dl><div><dt>Email</dt><dd>{student.email}</dd></div><div><dt>Visa</dt><dd>{student.visaStatus}</dd></div><div><dt>Target roles</dt><dd>{student.preferredPositions.join(", ")}</dd></div><div><dt>Skills</dt><dd>{student.skills.join(", ")}</dd></div></dl></div><div><h3>Top database matches</h3>{student.matches.map(match=><div className="admin-match" key={match.id}><span>{match.score}%</span><div><strong>{match.position}</strong><small>{match.company}</small></div></div>)}</div></div>:null}</article>)}</section>}
  </main>{editor!==undefined?<JobEditor job={editor} onClose={()=>setEditor(undefined)} onSaved={()=>{setEditor(undefined);router.refresh();}}/>:null}</div>;
}
